Add course Exercism
training-center/ruby-study-group pull request #11
Opened 2018-10-19 19:59 UTC by heliohead

2018-10-20 11:46 UTC, nelsonmfinda requested changes
Oi @heliohead :tada: 

O link [Exercism](https://exercism.io/tracks/ruby) não é para um curso, e sim para exercícios de programação utilizando Ruby :+1:  , @Diego-Brocanelli  sugiro que seja criado uma secção no material de estudo para incluir sites sobre *Coding Challenges* ou *Desafios de Programação* em Ruby.

Gostei do livro *Ruby Under a Miscroscope* :100: obrigado pela contribuição @heliohead

2018-10-20 11:50 UTC, nelsonmfinda commented
@heliohead  pode adicionar uma _descrição_ na sua *PR*? Assim ficaria mais fácil saber o que foi feito.

2018-10-20 13:01 UTC, heliohead commented
Achei que a mensagem do commit já era bem descritiva

2018-10-23 17:58 UTC, Diego-Brocanelli commented
Olá, @heliohead.

Toda PR para qualquer grupo de estudos do Training Center tem que conter uma descrição, fora a mensagem dos commits. Pois todos compõem a documentação do grupo de estudos.

Por favor inclua uma descrição para que possamos seguir com a análise da PR.

Obrigado.

2018-10-25 12:28 UTC, Diego-Brocanelli commented
Por favor, mantenha a lista em ordem alfabética.

2018-11-01 12:13 UTC, Diego-Brocanelli commented
Bom dia @heliohead 

Consta pendente alterações para aprovação da PR, poderia realiza-las por favor.

Att

2018-11-02 13:43 UTC, closed without merging